name: Before you ship
exclude:
- CONTRIBUTING.md
- Gemfile
- Gemfile.lock
- LICENSE.md
- README.md
- go
- vendor/

permalink: pretty

markdown: kramdown
kramdown:
  input: GFM

sass:
  style: :compressed

# Author/Organization info to be displayed in the templates
author:
  name: 18F
  url: https://18f.gsa.gov

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl: /assets/img/18f-logo.png
logoalt: 18F logo

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Overview
  url: ''
  internal: true
- text: Lifecycle of a Launch
  url: ato/
  internal: true
  children:
  - text: Checklist
    url: checklist/
    internal: true
  - text: Types
    url: types/
    internal: true
  - text: System Security Plan
    url: ssp/
    internal: true
  - text: Impact Levels
    url: levels/
    internal: true
  - text: Background
    url: background/
    internal: true
  - text: Tips
    url: tips/
    internal: true
- text: Security
  url: security/
  internal: true
  children:
  - text: Scanning
    url: scanning/
    internal: true
  - text: Static Analysis
    url: static-analysis/
    internal: true
  - text: Dynamic Scanning
    url: dynamic-scanning/
    internal: true
  - text: Frameworks
    url: frameworks/
    internal: true
  - text: Multi-Factor Authentication
    url: mfa/
    internal: true
- text: Infrastructure
  url: infrastructure/
  internal: true
  children:
  - text: Sandbox Accounts
    url: sandbox/
    internal: true
  - text: Amazon Web Services
    url: aws/
    internal: true
  - text: Good Production Practices
    url: good-production-practices/
    internal: true
  - text: Common Questions
    url: common-questions/
    internal: true
  - text: Monitoring
    url: monitoring/
    internal: true
  - text: Pinning Dependencies
    url: pinning-dependencies/
    internal: true
  - text: Logging
    url: logging/
    internal: true
- text: Laws
  url: laws/
  internal: true
  children:
  - text: 508 - Accessibility
    url: 508/
    internal: true
  - text: Paperwork Reduction Act (PRA)
    url: pra/
    internal: true
- text: Privacy
  url: privacy/
  internal: true

repos:
- name: Guides Template
  description: Main repository
  url: https://github.com/18F/before-you-ship

google_analytics_ua: UA-48605964-19

back_link:
  url: "https://pages.18f.gov/guides/"
  text: Read more 18F guides

styles:
  - assets/css/custom.css

collections:
  pages:
    output: true
    permalink: /:path/

defaults:
  -
    scope:
      path: ""
    values:
      layout: "guides_style_18f_default"

# Configuration for jekyll_pages_api_search plugin gem.
jekyll_pages_api_search:
  # Uncomment this to speed up site generation while developing.
  #skip_index: true

  # Each member of `index_fields` should correspond to a field generated by
  # the jekyll_pages_api. It can hold an optional `boost` member as a signal
  # to Lunr.js to weight the field more highly (default is 1).
  index_fields:
    title:
      boost: 10
    tags:
      boost: 10
    url:
      boost: 5
    body:
