name: Before you ship
baseurl: /before-you-ship
exclude:
- CONTRIBUTING.md
- Gemfile
- Gemfile.lock
- LICENSE.md
- README.md
- go
# exclude cached gems on Travis
# https://github.com/jekyll/jekyll/issues/2938#issuecomment-56237068
- vendor

permalink: pretty

markdown: kramdown
kramdown:
  input: GFM

sass:
  style: :compressed

# Author/Organization info to be displayed in the templates
author:
  name: 18F
  url: https://18f.gsa.gov

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl: /assets/img/18f-logo.png
logoalt: 18F logo

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Introduction
  url: ''
  internal: true
- text: Security
  url: security/
  internal: true
  children:
  - text: Personally Identifiable Information
    url: pii/
    internal: true
- text: ATOs
  url: ato/
  internal: true
  children:
  - text: Background
    url: background/
    internal: true
  - text: Levels
    url: levels/
    internal: true
  - text: Checklist
    url: checklist/
    internal: true
  - text: Tips
    url: tips/
    internal: true
  - text: System Security Plan
    url: ssp/
    internal: true
  - text: Authority to Test
    url: authority-to-test/
    internal: true
- text: Laws
  url: laws/
  internal: true
  children:
  - text: '508'
    url: 508/
    internal: true
  - text: PIA
    url: pia/
    internal: true
  - text: PRA
    url: pra/
    internal: true
  - text: SORN
    url: sorn/
    internal: true
- text: Infrastructure
  url: infrastructure/
  internal: true
  children:
  - text: Amazon Web Services
    url: aws/
    internal: true
  - text: Good Production Practices
    url: good-production-practices/
    internal: true
  - text: Common Questions
    url: common-questions/
    internal: true
- text: Vulnerability Scanning
  url: scanning/
  internal: true
- text: Static Security Analysis
  url: static-security-analysis/
  internal: true

repos:
- name: Guides Template
  description: Main repository
  url: https://github.com/18F/before-you-ship

google_analytics_ua: UA-48605964-19

back_link:
  url: "https://pages.18f.gov/guides/"
  text: Read more 18F Guides

scripts:
  - node_modules/@18f/private-eye/private-eye.js
  - assets/js/before-you-ship.js

styles:
  - assets/css/custom.css

collections:
  pages:
    output: true
    permalink: /:path/

defaults:
  -
    scope:
      path: ""
    values:
      layout: "guides_style_18f_default"
