title: Before You Ship
theme: uswds-jekyll
exclude:
  - CONTRIBUTING.md
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - vendor/

permalink: pretty

sass:
  style: :compressed

github_info:
  organization: 18F
  repository: before-you-ship
  default_branch: master

google_analytics_ua: UA-48605964-19

styles:
  - assets/css/custom.css

collections:
  pages:
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: ""
    values:
      layout: page
