name: Before you ship
baseurl: /before-you-ship
exclude:
- CONTRIBUTING.md
- Gemfile
- Gemfile.lock
- LICENSE.md
- README.md
- go
# exclude cached gems on Travis
# https://github.com/jekyll/jekyll/issues/2938#issuecomment-56237068
- vendor

permalink: pretty

markdown: kramdown
kramdown:
  input: GFM

sass:
  style: :compressed

# Author/Organization info to be displayed in the templates
author:
  name: 18F
  url: https://18f.gsa.gov

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl: /assets/img/18f-logo.png
logoalt: 18F logo

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Introduction
  url: ''
  internal: true
- text: Security
  url: security/
  internal: true
  children:
  - text: Personally Identifiable Information
    url: pii/
    internal: true
- text: ATOs, the 18F way
  url: ato/
  internal: true
- text: Infrastructure
  url: infrastructure/
  internal: true
  children:
  - text: Amazon Web Services
    url: aws/
    internal: true
  - text: Good Production Practices
    url: good-production-practices/
    internal: true 
- text: Vulnerability scanning
  url: zap/
  internal: true
- text: Static Analysis
  url: static-security-analysis/
  internal: true

repos:
- name: Guides Template
  description: Main repository
  url: https://github.com/18F/before-you-ship

google_analytics_ua: UA-48605964-19

back_link:
  url: "https://pages.18f.gov/guides/"
  text: Read more 18F Guides

collections:
  pages:
    output: true
    permalink: /:path/

defaults:
  -
    scope:
      path: ""
    values:
      layout: "guides_style_18f_default"
