name: Before you ship
exclude:
- CONTRIBUTING.md
- Gemfile
- Gemfile.lock
- LICENSE.md
- README.md
- go

permalink: pretty

markdown: kramdown
kramdown:
  input: GFM

sass:
  style: :compressed

# Author/Organization info to be displayed in the templates
author:
  name: 18F
  url: https://18f.gsa.gov

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl: /assets/img/18f-logo.png
logoalt: 18F logo

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Introduction
  url: ''
  internal: true
- text: Security
  url: security/
  internal: true
- text: ATOs, the 18F way
  url: ato/
  internal: true
- text: Amazon Web Services
  url: aws/
  internal: true
- text: Vulnerability scanning
  url: zap/
  internal: true

repos:
- name: Guides Template
  description: Main repository
  url: https://github.com/18F/before-you-ship

google_analytics_ua: UA-48605964-19

back_link:
  url: "https://pages.18f.gov/guides/"
  text: Read more 18F Guides

defaults:
  -
    scope:
      path: ""
    values:
      layout: "guides_style_18f_default"
